In [1]:
from BQ_ETL_Main import *

In [2]:
etl_bostondata()

/Users/colinpierce/Documents/AllDataProjects/DataSciProjects/BostonMarathon/BostonQual-scripts/BQ_ETL_Main.py:170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  speed_work_df[j][i] = True
/Users/colinpierce/Documents/AllDataProjects/DataSciProjects/BostonMarathon/BostonQual-scripts/BQ_ETL_Main.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  speed_work_df[j][i] = True
/Users/colinpierce/Documents/AllDataProjects/DataSciProjects/BostonMarathon/BostonQual-scripts/BQ_ETL_Main.py:227: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cross_training_df[j][i] = True
/Users/colinpierce/Documents/AllDataProjects/DataSciProjects/BostonMarathon/BostonQual-scripts/BQ_ETL_Main.py:232: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cross_training_df[j][i] = True

Boston Qualifier data successfully loaded

In [3]:
runner = extract_clean_data('runner')

In [4]:
runner

,level_0,index,Sex,Age,Height,Weight,BMI,First_Marathon,Years_Running,School_Running,Lifetime_Mileage,Year_Mileage,Amount_of_Races,Running_Program,Speed_Work,Cross_Training,Running_Club_or_Coach
0,0,0,Female,47,68.0,106.0,16.0,Shamrock,17.0,False,NaN,2740.0,1.0,True,True,True,False
1,1,1,Female,23,66.0,110.0,18.0,New York City Marathon,11.0,True,NaN,NaN,3.0,False,True,True,False
2,2,2,Female,46,66.0,110.0,18.0,NYC Marathon,7.0,False,5000.0,800.0,15.0,True,None,True,None
3,3,3,Male,55,64.0,112.0,19.0,California International,4.0,False,6000.0,2100.0,18.0,False,True,False,False
4,4,4,Female,35,62.0,113.0,21.0,Little Rock,2.0,False,2500.0,1250.0,2.0,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,371,371,Male,60,72.0,145.0,20.0,Toronto Waterfront,2.0,False,NaN,2200.0,2.0,False,False,False,False
372,372,372,Male,24,72.0,157.0,21.0,Marine Corps,13.0,True,13500.0,NaN,4.0,False,True,False,False
373,373,373,Male,51,70.0,165.0,24.0,Chicago,26.0,False,20043.0,2112.0,2.0,True,True,True,False
374,374,374,Male,25,71.0,130.0,18.0,Erie Marathon,12.0,True,20000.0,876.0,1.0,False,False,False,False
375,375,375,Male,38,69.0,137.0,20.0,Flying Pig,2.0,False,1000.0,745.0,5.0,True,False,False,False